import {
  ApplicationConfig,
  provideBrowserGlobalErrorListeners,
  provideZonelessChangeDetection,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import {
  provideHttpClient,
  withInterceptors,
} from '@angular/common/http';
import { appRoutes } from './app.routes';
import { jwtInterceptor } from './core/interceptors/jwt.interceptor';
import {
  LucideIconProvider,
  LUCIDE_ICONS,
} from 'lucide-angular';
import {
  LayoutDashboard,
  Building2,
  GitBranch,
  Settings,
  AlertTriangle,
  Copy,
  ArrowLeft,
  X,
  Clock,
  BarChart3,
  CircleCheck,
  CircleX,
  Users,
  Menu,
  Info,
  Eye,
  EyeOff,
  LogOut,
  UserPlus,
  Send,
  RefreshCw,
  XCircle,
  AlertCircle,
  Plus,
  Trash2,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  Check,
  Save,
  File,
  FileText,
  FileType,
  Wand2,
  Brain,
  MessageSquare,
  FileOutput,
  Layers,
  Zap,
  Server,
  Pencil,
  Loader2,
  Key,
  Lock,
  LockOpen,
  FileX,
  FolderPlus,
  Link,
  Search,
  MoreVertical,
  Tag,
  ArrowDown,
  LogIn,
  ArrowRightLeft,
  HelpCircle,
  UploadCloud,
  Loader,
  Files,
  Folder,
  Archive,
  Globe,
  Shield,
  Database,
  List,
  LayoutGrid,
  Undo2,
  RotateCcw,
} from 'lucide-angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZonelessChangeDetection(),
    provideRouter(appRoutes),
    provideHttpClient(withInterceptors([jwtInterceptor])),
    {
      provide: LUCIDE_ICONS,
      multi: true,
      useValue: new LucideIconProvider({
        LayoutDashboard,
        Building2,
        GitBranch,
        Settings,
        AlertTriangle,
        Copy,
        ArrowLeft,
        X,
        Clock,
        BarChart3,
        CircleCheck,
        CircleX,
        Users,
        Menu,
        Info,
        Eye,
        EyeOff,
        LogOut,
        UserPlus,
        Send,
        RefreshCw,
        XCircle,
        AlertCircle,
        Plus,
        Trash2,
        ChevronDown,
        ChevronUp,
        ChevronRight,
        Check,
        Save,
        File,
        FileText,
        FileType,
        Wand2,
        Brain,
        MessageSquare,
        FileOutput,
        Layers,
        Zap,
        Server,
        Pencil,
        Loader2,
        Key,
        Lock,
        LockOpen,
        FileX,
        FolderPlus,
        Link,
        Search,
        MoreVertical,
        Tag,
        ArrowDown,
        LogIn,
        ArrowRightLeft,
        HelpCircle,
        UploadCloud,
        Loader,
        Files,
        Folder,
        Archive,
        Globe,
        Shield,
        Database,
        List,
        LayoutGrid,
        Undo2,
        RotateCcw,
      }),
    },
  ],
};
